export const company_columns = [
  {name: "Copmany name", uid: "company_name"},
  {name: "Company domain", uid: "company_domain"},
  {name: "Company type", uid: "company_type"},
  {name: "Products", uid: "products"},
  {name: "Creation date", uid: "creation_date"},
  {name: "Last update", uid: "last_update"},
  {name: "Actions", uid: "actions"},
];

export const company_users = [
  {
    id: 1,
    company_name: "Tony Reichert",
    company_domain: "comapny.com",
    company_type: "purchaser",
    products: ["product 1","product 2", "product 3" ],
    creation_date: "12/10/2024",
    last_update: "12/10/2024",
    actions: "edit",
  },
  {
    id: 2,
    company_name: "Tony Reichert",
    company_domain: "comapny.com",
    company_type: "purchaser",
    products: ["product 1"],
    creation_date: "12/10/2024",
    last_update: "12/10/2024",
    actions: "edit",
  },
  {
    id: 3,
    company_name: "Tony Reichert",
    company_domain: "comapny.com",
    company_type: "purchaser",
    products: ["product 1"],
    creation_date: "12/10/2024",
    last_update: "12/10/2024",
    actions: "edit",
  },
  {
    id: 4,
    company_name: "Tony Reichert",
    company_domain: "comapny.com",
    company_type: "purchaser",
    products: ["product 1","product 2", "product 3"],
    creation_date: "12/10/2024",
    last_update: "12/10/2024",
    actions: "edit",
  },
  {
    id: 5,
    company_name: "Tony Reichert",
    company_domain: "comapny.com",
    company_type: "purchaser",
    products: ["product 1"],
    creation_date: "12/10/2024",
    last_update: "last_update",
    actions: "edit",
  },
];
