export const company_columns = [
  {name: "Copmany name", uid: "company_name"},
  {name: "Company domain", uid: "company_domain"},
  {name: "Company type", uid: "company_type"},
  {name: "Products", uid: "products"},
  {name: "Creation date", uid: "creation_date"},
  {name: "Last update", uid: "last_update"},
  {name: "Actions", uid: "actions"},
];

export const users_columns = [
  {name: "Copmany", uid: "company"},
  {name: "First name", uid: "f_name"},
  {name: "Last name", uid: "l_name"},
  {name: "Email", uid: "email"},
  {name: "Position", uid: "position"},
  {name: "Role", uid: "role"},
  {name: "Creation date", uid: "c_date"},
  {name: "Last Update", uid: "l_update"},
  {name: "Invitation Status", uid: "i_status"},
  {name: "Actions", uid: "actions"},
];
export const company_users = [
  {
    id: 1,
    company_name: "Tony Reichert",
    company_domain: "comapny.com",
    company_type: "purchaser",
    products: ["product 1","product 2", "product 3" ],
    creation_date: "12/10/2024",
    last_update: "12/10/2024",
    actions: "edit",
  },
  {
    id: 2,
    company_name: "Tony Reichert",
    company_domain: "comapny.com",
    company_type: "purchaser",
    products: ["product 1"],
    creation_date: "12/10/2024",
    last_update: "12/10/2024",
    actions: "edit",
  },
  {
    id: 3,
    company_name: "Tony Reichert",
    company_domain: "comapny.com",
    company_type: "purchaser",
    products: ["product 1"],
    creation_date: "12/10/2024",
    last_update: "12/10/2024",
    actions: "edit",
  },
  {
    id: 4,
    company_name: "Tony Reichert",
    company_domain: "comapny.com",
    company_type: "purchaser",
    products: ["product 1","product 2", "product 3"],
    creation_date: "12/10/2024",
    last_update: "12/10/2024",
    actions: "edit",
  },
  {
    id: 5,
    company_name: "Tony Reichert",
    company_domain: "comapny.com",
    company_type: "purchaser",
    products: ["product 1"],
    creation_date: "12/10/2024",
    last_update: "last_update",
    actions: "edit",
  },
];

export const users = [
  {
    id: 1,
    company: "Tony Reichert",
    f_name: "Richard",
    l_name: "Branco",
    email: "richard@gmail.com",
    position: "Head of Sales",
    role: "Admin",
    c_date: "12/10/2024",
    l_update: "12/10/2024",
    i_status: "Sent",
    actions: "edit",
  },
  {
    id: 2,
    company: "Tony Reichert",
    f_name: "Muhammad",
    l_name: "Tayyab",
    email: "tayyab@gmail.com",
    position: "Head of Sales",
    role: "User",
    c_date: "12/10/2024",
    l_update: "12/10/2024",
    i_status: "Activated",
    actions: "edit",
  },
  {
    id: 3,
    company: "Tony Reichert",
    f_name: "Richard",
    l_name: "Branco",
    email: "richard@gmail.com",
    position: "Head of Sales",
    role: "Admin",
    c_date: "12/10/2024",
    l_update: "12/10/2024",
    i_status: "Sent",
    actions: "edit",
  },
  {
    id: 4,
    company: "Tony Reichert",
    f_name: "Muhammad",
    l_name: "Tayyab",
    email: "tayyab@gmail.com",
    position: "Head of Sales",
    role: "User",
    c_date: "12/10/2024",
    l_update: "12/10/2024",
    i_status: "Activated",
    actions: "edit",
  },
  {
    id: 5,
    company: "Tony Reichert",
    f_name: "Richard",
    l_name: "Branco",
    email: "richard@gmail.com",
    position: "Head of Sales",
    role: "Admin",
    c_date: "12/10/2024",
    l_update: "12/10/2024",
    i_status: "Sent",
    actions: "edit",
  },
  {
    id: 6,
    company: "Tony Reichert",
    f_name: "Muhammad",
    l_name: "Tayyab",
    email: "tayyab@gmail.com",
    position: "Head of Sales",
    role: "User",
    c_date: "12/10/2024",
    l_update: "12/10/2024",
    i_status: "Activated",
    actions: "edit",
  },
];
